
[genpushover]
# APP ID
# account
appid = abc123

# USER ID
#  acct
# To send notifications to more than one person, enter multiple Pushover
# user (or group) keys separated by spaces and/or commas, e.g.:
# userid = 123abc 456def 789ghi
userid = 123abc

# Notification sound
# Full list at https://pushover.net/api#sounds
pushsound = updown

# number of seconds to retry sending a failed message
max_retry_time = 600

# the number of seconds to wait before sending a failed message
default_wait = 120
